language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter || true
addons:
  code_climate:
    repo_token: 3cca4d10a51839bc5d115d41a0c12b98cbdb27a21e9c86544324fa028b799b84
